### ISSUE TITLE
Not Compatible with Gravity Forms 2.5

### ISSUE THREAD

**Issue by jeremiahbenes** [ConvertKit/convertkit-gravity-forms#34]
The plugin is incompatible with Gravity Forms 2.5+. When creating a feed and selecting a form, the dropdown is blank. 

DevTools logs the following error:

```
Uncaught ReferenceError: gform is not defined
at admin.php?page=gf_edit_forms&view=settings&subview=ckgf&id=2&fid=0:3

Uncaught ReferenceError: gform is not defined
at admin.php?page=gf_edit_forms&view=settings&subview=ckgf&id=2&fid=0:15```

**Comment by DigitalServicesLab** [comment]
You can temporarily fix this by re-defining $field within settings_convertkit_form() around line 224 of class-gf-convertkit.php

The problem seems to be that what is passed into this function is a large object, not an array. The GF documentation is a little unclear (at least to me) on what it passed into custom field type callbacks. 

I added the following inside the function and the plugin works again. 
`			
// ADDED TO MAKE THIS PLUGIN WORK: passed in $field value is an large object - needs to be an array containing the configuration options of this field 
			$field = array(
				'name'     => 'form_id',
				'label'    => __( 'ConvertKit Form' ),
				'type'     => 'convertkit_form',
				'required' => true,
				'tooltip'  => sprintf( '<h6>%s</h6>%s', __( 'ConvertKit Form', 'convertkit' ), __( 'Select the ConvertKit form that you would like to add your contacts to.', 'convertkit' ) ),
			);
`

**Comment by corydhmiller** [comment]
@jeremiahbenes We just pushed out 1.2.0 that includes compatibility for Gravity Forms 2.5.
